### ISSUE TITLE
Unable to get the Content of HTML email component stored in Blob

### ISSUE THREAD

**Issue by abhi004** [KevM/tikaondotnet#92] opened 2017-03-30 04:45 UTC
Hi ,
I am writing HTML formated email<HTML></HTML> to Azure blob and trying to read the blob content by passing the uri but TikaOnDotNet extractor is returning nothing

**Comment by KevM** [comment] 2017-03-31 00:42
I confirmed this and am working on a fix. Not sure why the native Tika
mechanism is working weirdly.

It is easy to do this your self. Just download the bytes of the web page
and call the Extract(byte[]) overload.

**Comment by abhi004** [comment] 2017-03-31 04:24
Thanks Kev ,
I have tried that as well to write into stream but it shows same exception 

var bytes = default(byte[]);
                    using (var memstream = new MemoryStream())
                    {

                        bytes = blob.OpenRead().ToByteArray();
                        var textExtractors = new TextExtractor();
                        var Contentss = textExtractors.Extract(bytes);

Another issue is when you use Nuget package in Azure functions to import TikaOnDotNet it complains about mismatch in assembly .

**Comment by KevM** [comment] 2017-03-31 14:01
Are you trying to extract text from the Azure blob or store the results a web URL (html) into a blob?

I would double check that the bytes you are putting into Tika are what you are expecting. More details on what you are attempting would be helpful.

**Comment by KevM** [comment] 2017-03-31 14:47
Ah I see the same output when I am manually downloading the page. I seems that our `ContentHandler` events are not getting all the contents of the page.

**Comment by KevM** [comment] 2017-03-31 15:18
Duplicate of #84. Moving the conversation about this problem there.

**Closed by KevM** 2017-03-31 15:18 UTC
