### ISSUE TITLE
Where is SolutionInfo.cs?

### ISSUE THREAD

**Issue by harrchen** [KevM/tikaondotnet#50] opened 2016-04-30 13:31 UTC
The project has a link to SolutionInfo.cs but that file is not part of the source.  Is it needed?  If so, where I can find it?

**Comment by KevM** [comment] 2016-05-01 18:48
Build the app from the command line. If the readme doesn't already say this it should.

**Comment by KevM** [comment] 2016-05-01 18:49
https://github.com/KevM/tikaondotnet/blob/master/Readme.md

**Comment by harrchen** [comment] 2016-05-01 18:59
When I tried to use build.cmd, I ran into other issues (also submitted).  I finally just removed the SolutionInfo.cs reference from project and it built fine with Visual Studio.

**Comment by KevM** [comment] 2016-05-02 04:04
This is a duplicate of #49.

**Closed by KevM** 2016-05-02 04:04 UTC
